- name: Add Microsoft Visual Studio Code Repo
  become: yes
  yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: Install/Update VSCode
  become: yes
  dnf:
    name: code
    state: latest

- name: Increase max file watches to maximum allowed (for vscode)
  become: yes
  sysctl:
    name: fs.inotify.max_user_watches
    value: 524288
    state: present