- name: Enable RPM Fusion Repos
  dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
  become: yes
  when: ansible_distribution == 'Fedora'